Minor update "Time sync"
Adlink-ROS/roscube-doc pull request #19
Opened 2022-05-31 03:01 UTC by DanielHo-BS

1. Update the images
2. Update the camera trigger

2022-05-31 08:19 UTC, evshary requested changes

2022-05-31 08:19 UTC, evshary commented on application_note/time_sync/software_configuration.rst
> +    sudo python3 adlink_camera_sync sync -f 5 -t 5
Great! Thanks for the update.
Please also update the "Time Synchronization" page.

2022-05-31 09:17 UTC, DanielHo-BS commented on application_note/time_sync/software_configuration.rst
> +    sudo python3 adlink_camera_sync sync -f 5 -t 5
OK, I will update this page.

2022-05-31 09:19 UTC, DanielHo-BS commented
Update the "Time Synchronization" page.
1. update usage of camera trigger daemon
2. remove the "sensor_subscriber" function from sensors_pkg

2022-06-01 06:20 UTC, evshary commented
LGTM.

2022-06-01 06:20 UTC, merged